### ISSUE TITLE
Rendering of train tracks fails to track map zoom properly with complex network.

### ISSUE THREAD

**Issue by SabrCat** [Zhincore/dynmap-trains#2]
I think this is best shown off in **a video**:

https://github.com/Zhincore/dynmap-trains/assets/56313836/1613b78a-dbc9-44d7-951f-ef053924016e

If you can't watch the video right now, the TL:DR is: When loading the map from switching layers, the rails are properly aligned, even when moving around. But as soon as one zooms in, the rails zoom in either too much or too little and then also move wrong, becoming misaligned with the map. Some trains also appear to no longer be visible on the map. The separate track map browser page appears to be showing all rails correctly, though some trains seem to be missing from track map too. That page has become a little bit laggy with the amount of signal spam my custom wagon loading stations require. Also, for reference, the big upper train testing platform in the video is about 1200 blocks wide. 

**A screenshot of create trackmap** (With rough size annotation)
![image](https://github.com/Zhincore/dynmap-trains/assets/56313836/86fc6806-9fea-4806-9948-c6f22186b0e2)

This only became an issue recently as our rail network kept growing, originally this worked perfectly fine and I have made no major changes since. 

Do you have any idea why this may be happening, and if there is a fix? Thanks in advance!

**Comment by SabrCat** [comment]
![image](https://github.com/Zhincore/dynmap-trains/assets/56313836/e19155c3-3d96-4b4e-99f8-24f14f9f2193)

Here are the error messages the browser shows. The larger one with jquery only occurs when actively zooming, the bottom most message keeps happening again every second.

**Comment by SabrCat** [comment]
I have looked at the /api/network and /api/trains endpoints, both appear to provide valid json that is not truncated to the browser displaying text (though I did notice an oddity in that all trains show an owner of null). However, the json for the network is ~780,000 characters long. Maybe that's causing the issue with something overflowing?

**Comment by Zhincore** [comment]
Hi!
That's a beautiful network you have there, first of all.
It seems like my code is taking too long to process all the data in reasonable time and that might be why it fails to render properly.
I have to optimize my code to handle such situations better, hopefully I will publish an update in the upcoming days.
Thank you for your issue! You've provided me with valuable information about the problem!

**Comment by SabrCat** [comment]
Okay, cool! 
I've also talked to some people from the trackmap discord, it seems that trains disappearing from the map was also an issue in the later stages of their SMP, though they weren't sure whether it was TPS or trackmap. 
My TPS are just fine, so the issue seems to be with the mod. And as the JSON from the API looks correct, I believe the issue is with the respective frontend. Even the trackmap frontend can no longer keep up, trains are missing there too. I submitted a support ticked with them, but their sole dev is currently busy with other things, so I am not expecting a fix from them anytime soon. 
I hope your optimization will make things work again, as our network is likely still going to grow to beyond tenfold of what it is currently, and debugging that without trackmap would be quite difficult. 
Thanks again for your work on this!

**Comment by Zhincore** [comment]
Hi @HB-Stratos!
Could you try out the [release v1.2](https://github.com/Zhincore/dynmap-trains/releases/tag/v1.2)? I am hoping this release shouldn't lag the browser and perform better. I haven't tested on a big network, so I am not sure how well it will behave. I am looking forward for your feedback!

**Comment by PatatjeMC** [comment]
![image](https://github.com/Zhincore/dynmap-trains/assets/85753923/95d7b7bc-e459-4986-bb24-18ec21b6abef)
it doesn't seem to have changed much this is with the v1.2 version

**Comment by Zhincore** [comment]
Ouch, sorry about that. But the error has changed! That sure means something! Also I don't see any tracks on your screenshot, did they just disappear?

EDIT: Oh I see them! They're just really small, right?

**Comment by SabrCat** [comment]
That wasn't me who commented. I haven't gotten around to testing 1.2 yet. However I can report that even without it a mod update of various mods as well as a server restart has solved the zoom breaking everything. The "took too long" errors still appear and the page is a bit laggy, but no longer broken. All this without any change to trains.js.

**Comment by Zhincore** [comment]
It's fine, it seems like they are having similar issue, more testers is better haha.
I'm glad it's no longer broken for you, maybe there was something weird going on with CTM.

**Comment by SabrCat** [comment]
![image](https://github.com/Zhincore/dynmap-trains/assets/56313836/e1bb08e9-b54a-4e0a-9e48-d0730bf381b7)
Well, I upgraded to 1.2, and the issue is back. Tracks render in completely wrong locations and gets messed up more with every time one zooms in or out. It was working earlier, but it has ceased to do so. At this point I would say that this is some global state corruption that would have happend with the old and the new version. Not fully sure. 
I should add that trackmap itself is also broken and missing trains again.

**Comment by Zhincore** [comment]
That is weird... Really unexpected... Did you try downgrading to v1.1?

**Comment by SabrCat** [comment]
I can't do that at the moment as there are five other players online. I will try that later. Currently the server is also under harder load than usual due to the increased number of players, so this time TPS may or may not also be causing an issue. We're sitting at ~40-45 MSPT, and the TPS occasionally drop to ~18, then to 21, then recover.

**Comment by SabrCat** [comment]
[trains.json](https://github.com/Zhincore/dynmap-trains/files/13030918/trains.json)
[blocks.json](https://github.com/Zhincore/dynmap-trains/files/13030919/blocks.json)
[signals.json](https://github.com/Zhincore/dynmap-trains/files/13030920/signals.json)
[network.json](https://github.com/Zhincore/dynmap-trains/files/13030921/network.json)
[config.json](https://github.com/Zhincore/dynmap-trains/files/13030922/config.json)
[style.css.txt](https://github.com/Zhincore/dynmap-trains/files/13030926/style.css.txt)

I have taken all the api outputs from trackmap and saved them to individual files. Perhaps this can help you detect whether the json itself is faulty, or if the issue is somewhere else.

**Comment by Zhincore** [comment]
Thank you so much! May I also ask what update interval you have set in CTM? Setting it to longer periods may help

**Comment by SabrCat** [comment]
It is set to the default 0.5s as seen in config.json
I don't think I can change that setting without restarting the server, so that test will have to wait till the server is less busy.

**Comment by SabrCat** [comment]
```
[18:55:43] [TrackMap watcher/WARN]: Exception during update loop
[18:55:43] [TrackMap watcher/INFO]: [STDERR]: java.util.ConcurrentModificationException
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1630)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1628)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at littlechasiu.ctm.TrackWatcher.update(TrackWatcher.kt:397)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at littlechasiu.ctm.TrackWatcher.watch(TrackWatcher.kt:61)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at littlechasiu.ctm.TrackWatcher.access$watch(TrackWatcher.kt:24)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at littlechasiu.ctm.TrackWatcher$watch$1.invokeSuspend(TrackWatcher.kt)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:493)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at littlechasiu.ctm.TrackWatcher$start$1.invoke(TrackWatcher.kt:40)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at littlechasiu.ctm.TrackWatcher$start$1.invoke(TrackWatcher.kt:39)
[18:55:43] [TrackMap watcher/INFO]: [STDERR]:   at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```
I also came across this error in my server log, maybe that explains some of the issues?

**Comment by Zhincore** [comment]
Hmm, that could be causing some issues, indeed.

**Comment by calliecameron** [comment]
I'm having the same issue. I'm using v1.3, I've increased the update interval in CTM to 2 as suggested, and I don't have the TrackMap watcher errors in my server log. However, I'm getting a different error in the js log in the browser:

```
Uncaught TypeError: car.leading is undefined
    update trains.js:459
    #updateLayer trains.js:763
    update trains.js:769
    RenderManager trains.js:717
    jQuery 7
    initialize map.js:186
    fire Events.js:203
    _moveEnd Map.js:1241
    _onZoomTransitionEnd Map.js:1717
    z Util.js:231
    _onZoomTransitionEnd Map.js:1716
    setTimeout handler*_animateZoom Map.js:1701
    _tryAnimatedZoom Map.js:1672
    z Util.js:231
    _tryAnimatedZoom Map.js:1669
    setView Map.js:195
    setZoomAround Map.js:249
    _performZoom Map.ScrollWheelZoom.js:83
    setTimeout handler*_onWheelScroll Map.ScrollWheelZoom.js:57
    s DomEvent.js:108
trains.js:459:13
```

Only some of my trains are showing up - and the same is true in CTM. In the json from /api/trains, 'leading' is missing on some of the cars.

**Comment by calliecameron** [comment]
Actually, I get different errors in chrome and firefox: the previous error is from firefox. In chrome I get:

```trains.js:459 Uncaught 
TypeError: Cannot read properties of undefined (reading 'dimension')
    at TrainRenderer.update (trains.js:459:25)
    at #updateLayer (trains.js:763:18)
    at RenderManager.update (trains.js:769:26)
    at DynMap.<anonymous> (trains.js:717:14)
    at DynMap.dispatch (jquery-3.5.1.js?_=3.7-beta-4-935:5429:27)
    at elemData.handle (jquery-3.5.1.js?_=3.7-beta-4-935:5233:28)
    at Object.trigger (jquery-3.5.1.js?_=3.7-beta-4-935:8715:12)
    at DynMap.<anonymous> (jquery-3.5.1.js?_=3.7-beta-4-935:8793:17)
    at Function.each (jquery-3.5.1.js?_=3.7-beta-4-935:381:19)
    at jQuery.fn.init.each (jquery-3.5.1.js?_=3.7-beta-4-935:203:17)
```

I've defined all the dimensions in dynmap/worlds.txt, dynmap/configuration.txt, and config/create-track-map.json.

The glitchy zooming behaviour is the same in both browsers.

**Comment by calliecameron** [comment]
Going by https://github.com/jenchanws/create-track-map/issues/55, the missing trains could be caused by derailed trains not having car.leading - this may be a separate issue from the glitchy zooming.

**Comment by calliecameron** [comment]
Created https://github.com/Zhincore/dynmap-trains/issues/12 for handling the derailed trains.

Also, I noticed that it's only the track that glitches when zooming - trains (if they show up) stay in the right place.

**Comment by calliecameron** [comment]
With the latest version from https://github.com/Zhincore/dynmap-trains/issues/12#issuecomment-2293309791, glitchy zooming is fixed. Tested on firefox, chrome and chrome for android.
